
// Auto-generated by Antigravity to sync network for mobile QR access
// This IP must match the host machine running 'npm run dev'
// If you see 'ERR_CONNECTION_REFUSED' on mobile, check your current IP (ipconfig)
export const NETWORK_CONFIG = {
    localIp: '192.168.8.118', // UPDATE THIS IF YOUR NETWORK CHANGES
    port: '3000'
};
